require(roxygen2)
require(devtools)
devtools::load_all("~/repos/bayou/bayou_1.0/")
document("~/repos/bayou/bayou_1.0/")

isis <- read.csv("../data/NORMALS.csv")
isis$SPECIES <- sapply(isis$SPECIES, function(x) simpleCap(gsub(" ", "_", tolower(x))))
isis.mean <- dcast(isis[,1:3], SPECIES~TEST, mean, na.rm=TRUE); isis.sd <- dcast(isis[,c(1,2,4)], SPECIES~TEST, mean, na.rm=TRUE);isis.N <- dcast(isis[,c(1,2,5)], SPECIES~TEST, sum, na.rm=TRUE)
colnames(isis.sd)[-(1)] <- paste(colnames(isis.sd)[-(1)],"SD", sep="."); colnames(isis.N)[-(1)] <- paste(colnames(isis.N)[-(1)],"N", sep=".")
isis <- left_join(isis.mean, isis.sd, by="SPECIES") %>% left_join(., isis.N, by="SPECIES")
colnames(isis) <- gsub(" ", "", colnames(isis))
colnames(isis) <- gsub("(", "_", colnames(isis), fixed=TRUE)
colnames(isis) <- gsub(")", "", colnames(isis), fixed=TRUE)
colnames(isis) <- gsub(":", "_", colnames(isis), fixed=TRUE)
colnames(isis) <- gsub("-", "", colnames(isis), fixed=TRUE)
colnames(isis) <- gsub("_.", ".", colnames(isis), fixed=TRUE)
colnames(isis) <- gsub("Temperature_", "Temperature", colnames(isis), fixed=TRUE)
saveRDS(isis, "../data/species360.rds")
